version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dcode
    main: ./cmd/dcode
    binary: dcode
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: dcode
    builds: [dcode]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Other changes
      order: 999

release:
  github:
    owner: Dhanuzh
    name: dcode
  draft: false
  prerelease: auto
  name_template: "dcode {{.Tag}}"

brews:
  - name: dcode
    repository:
      owner: Dhanuzh
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/Dhanuzh/dcode"
    description: "AI-powered terminal coding agent with multi-provider support"
    license: "MIT"
    skip_upload: auto
    install: |
      bin.install "dcode"
    test: |
      system "#{bin}/dcode", "version"
